### ISSUE TITLE
GitHub profile not updating stats automatically when I put a GitHub username that it entered before

### ISSUE THREAD

**Issue by lulunac27a** [hyochan/github-stats#29]
This GitHub Readme Stats needs to be updated automatically like every day, because when I put my GitHub username for the first time, it will get the stats for my users, but when I put my GitHub username that I've entered before, it doesn't update the stats.

**Comment by hyochan** [comment]
@lulunac27a Hi! Thank you for the interest on my `github-stats` 🙂
Currently, the api caches the result for 3hours https://github.com/hyochan/github-stats/blob/12eda2fab55acd51e5a244adb5aff82d5548a9a0/server/services/githubService.ts#L592-L601

Therefore, it seems like your question is already qualified 🤔

**Comment by lulunac27a** [comment]
My GitHub stats generated from this repository are not updated at all. 
<img width="564" alt="Screenshot 2023-11-10 at 11 01 08 PM" src="https://github.com/hyochan/github-stats/assets/100660343/a9b006f3-b958-43e8-a591-3c7b781b0ea9">
instead of 
<img width="142" alt="Screenshot 2023-11-10 at 11 00 51 PM" src="https://github.com/hyochan/github-stats/assets/100660343/d0400030-f28d-4984-849d-1174bdd80d7e"><img width="151" alt="Screenshot 2023-11-10 at 10 58 08 PM" src="https://github.com/hyochan/github-stats/assets/100660343/5ce088f8-9345-40a6-8ce3-970dded73c46">

**Comment by hyochan** [comment]
> My GitHub stats generated from this repository are not updated at all. <img alt="Screenshot 2023-11-10 at 11 01 08 PM" width="564" src="https://user-images.githubusercontent.com/100660343/282219927-a9b006f3-b958-43e8-a591-3c7b781b0ea9.png"> instead of <img alt="Screenshot 2023-11-10 at 11 00 51 PM" width="142" src="https://user-images.githubusercontent.com/100660343/282219917-d0400030-f28d-4984-849d-1174bdd80d7e.png"><img alt="Screenshot 2023-11-10 at 10 58 08 PM" width="151" src="https://user-images.githubusercontent.com/100660343/282219809-5ce088f8-9345-40a6-8ce3-970dded73c46.png">

I might have to look into github api then 🤔
Thanks for reporting!

**Comment by lulunac27a** [comment]
My GitHub stats have still not been updated for more than 3 weeks, it's should been updated right now

**Comment by hyochan** [comment]
@lulunac27a I think https://github.com/hyochan/github-stats/commit/afb8b8c741dfc2819f354a65223446ddd663d684 will fix this issue! Let's see how it goes.

**Comment by hyochan** [comment]
It looks like the issue is related https://github.com/vercel/next.js/issues/47273
I've updated nextjs version and let's see if this is working.

**Comment by lulunac27a** [comment]
The [stats.dooboo.io homepage](https://stats.dooboo.io/en) updated properly, but the [stats.dooboo.io/en/stats](https://stats.dooboo.io/en/stats/) link after entering my GitHub username from [stats.dooboo.io homepage](https://stats.dooboo.io/en) then click **Find out more**, it still doesn't update my detailed stats.

**Comment by hyochan** [comment]
@lulunac27a Could you try once again? The site has just published like 5 minutes ago 😅.

**Comment by lulunac27a** [comment]
The [stats.dooboo.io/en/stats](https://stats.dooboo.io/en/stats/) link is updated, so it's now working properly.

**Comment by hyochan** [comment]
@lulunac27a Congrats!

**Comment by lulunac27a** [comment]
How to update my GitHub stats from [stats.dooboo.io](https://stats.dooboo.io/) every day?

**Comment by hyochan** [comment]
> How to update my GitHub stats from [stats.dooboo.io](https://stats.dooboo.io/) every day? Because the stats are not updating for few days now and need to be updated.

It will be updated automatically if you put generated stats to you github readme like below.

<img width="720" alt="Screenshot 2023-12-03 at 4 40 48 AM" src="https://github.com/hyochan/github-stats/assets/27461460/f707f211-bbbf-4b3b-b9af-ad55cac5a0a9">

**Comment by lulunac27a** [comment]
I put this in my Gitub README Profile but it's not updating for like a week now.
<img width="886" alt="Screenshot 2023-12-03 at 8 57 08 AM" src="https://github.com/hyochan/github-stats/assets/100660343/27f17e2a-8cff-4868-a879-643636420f75">

**Comment by hyochan** [comment]
@lulunac27a Thanks for reporting this again! I've just fixed the logical error and it will work after the deployment!

I am really sorry for the inconvenience 😓

**Comment by lulunac27a** [comment]
Thank you for fixing this problem. So my stats are now updating every day.
