### ISSUE TITLE
[bug] dark mode styling not applied when div expands after search

### ISSUE THREAD

**Issue by jdegand** [hyochan/github-stats#31]
![hyochan-github-stats](https://github.com/hyochan/github-stats/assets/70610011/941a7809-85fa-4dda-8dbb-b16823f133bb)

The image shows the issue.  When the div expands after search, the light mode styling appears in dark mode.  

I believe the issue is caused by a div with this css code: `self-stretch bg-cover flex flex-col justify-center items-center max-[425px]:p-0`.  

If you replace `bg-cover` with `bg-paper`, the styling will be applied.  I don't believe `bg-cover` is necessary on that div and I noticed no difference without its rule being applied.

**Comment by hyochan** [comment]
@jdegand You are right! Just resolved in https://github.com/hyochan/github-stats/commit/12dd415d90cfdb8e18bb0541e247a931a55ed91a
